using System;
using System.Collections.Generic;

namespace Logix.Application.DTOs.ACC
{
    public class AccFacilitiesVwDto
    {
        public long FacilityId { get; set; }
        public string? FacilityName { get; set; }
        public string? FacilityName2 { get; set; }
        public string? FacilityLogo { get; set; }
        public string? FacilityPhone { get; set; }
        public string? FacilityMobile { get; set; }
        public string? FacilityEmail { get; set; }
        public string? FacilitySite { get; set; }
        public string? FacilityAddress { get; set; }
        public int? InsertUserId { get; set; }
        public int? UpdateUserId { get; set; }
        public int? DeleteUserId { get; set; }
        public DateTime? InsertDate { get; set; }
        public DateTime? UpdateDate { get; set; }
        public DateTime? DeleteDate { get; set; }
        public bool? FlagDelete { get; set; }
        public string? BillHeader { get; set; }
        public string? BillFooter { get; set; }
        public long? AccountCash { get; set; }
        public long? AccountChequ { get; set; }
        public long? AccountCustomer { get; set; }
        public long? AccountInvestor { get; set; }
        public long? AccountSupplier { get; set; }
        public long? AccountChequUnderCollection { get; set; }
        public long? AccountCostSales { get; set; }
        public long? AccountSalesProfits { get; set; }
        public long? AccountInstallmentsUnderCollection { get; set; }
        public long? AccountInvestorProfits { get; set; }
        public long? AccountSales { get; set; }
        public long? AccountFeeManage { get; set; }
        public long? AccountProfitInstallment { get; set; }
        public long? AccountProfitInstallmentDeferred { get; set; }
        public long? AccountMerchandiseInventory { get; set; }
        public long? AccountCostGoodsSold { get; set; }
        public long? AccountCashSales { get; set; }
        public long? AccountReceivablesSales { get; set; }
        public long? AccountInventoryTransit { get; set; }
        public long? AccountBranches { get; set; }
        public string? AccountNameCash { get; set; }
        public string? AccountCodeCash { get; set; }
        public string? AccountNameChequ { get; set; }
        public string? AccountCodeChequ { get; set; }
        public string? AccountNameCustomer { get; set; }
        public string? AccountCodeCustomer { get; set; }
        public string? AccountNameInvestor { get; set; }
        public string? AccountCodeInvestor { get; set; }
        public string? AccountNameSupplier { get; set; }
        public string? AccountCodeSupplier { get; set; }
        public string? AccountNameChequUnderCollection { get; set; }
        public string? AccountCodeChequUnderCollection { get; set; }
        public string? AccountNameSales { get; set; }
        public string? AccountCodeSales { get; set; }
        public string? AccountNameFeeManage { get; set; }
        public string? AccountCodeFeeManage { get; set; }
        public string? AccountNameProfitInstallment { get; set; }
        public string? AccountCodeProfitInstallment { get; set; }
        public string? AccountNameProfitInstallmentDeferred { get; set; }
        public string? AccountCodeProfitInstallmentDeferred { get; set; }
        public string? AccountNamemerchandiseInventory { get; set; }
        public string? AccountCodemerchandiseInventory { get; set; }
        public string? AccountNameCostGoodsSold { get; set; }
        public string? AccountCodeCostGoodsSold { get; set; }
        public string? AccountNameCashSales { get; set; }
        public string? AccountCodeCashSales { get; set; }
        public string? AccountNameReceivablesSales { get; set; }
        public string? AccountCodeReceivablesSales { get; set; }
        public string? AccountNameInventoryTransit { get; set; }
        public string? AccountCodeInventoryTransit { get; set; }
        public string? AccountNameBranches { get; set; }
        public string? AccountCodeBranches { get; set; }
        public string? AccountNameCostSales { get; set; }
        public string? AccountCodeCostSales { get; set; }
        public string? AccountNameSalesProfits { get; set; }
        public string? AccountCodeSalesProfits { get; set; }
        public string? AccountNameInstallmentsUnderCollection { get; set; }
        public string? AccountCodeInstallmentsUnderCollection { get; set; }
        public string? AccountNameInvestorProfits { get; set; }
        public string? AccountCodeInvestorProfits { get; set; }
        public string? GroupIncameName { get; set; }
        public string? GroupIncameCode { get; set; }
        public string? GroupExpensesName { get; set; }
        public string? GroupExpensesCode { get; set; }
        public string? GroupAssetsCode { get; set; }
        public string? GroupAssetsName { get; set; }
        public string? GroupLiabilitiesName { get; set; }
        public string? GroupLiabilitiesCode { get; set; }
        public string? GroupCopyrightsName { get; set; }
        public string? GroupCopyrightsCode { get; set; }
        public string? AccountContractorsName { get; set; }
        public string? AccountContractorsCode { get; set; }
        public string? CustomerCode { get; set; }
        public string? CustomerName { get; set; }
        public long? GroupIncame { get; set; }
        public long? GroupExpenses { get; set; }
        public long? GroupAssets { get; set; }
        public long? GroupLiabilities { get; set; }
        public long? GroupCopyrights { get; set; }
        public long? AccountContractors { get; set; }
        public long? CcIdProjects { get; set; }
        public int? LnkInoviceInventory { get; set; }
        public int? LnkBillInventroy { get; set; }
        public string? AccountDiscountName { get; set; }
        public string? AccountDiscountCode { get; set; }
        public long? DiscountAccountId { get; set; }
        public long? DiscountCreditAccountId { get; set; }
        public string? AccountDiscountCreditName { get; set; }
        public string? AccountDiscountCreditCode { get; set; }
        public string? HeaderName { get; set; }
        public string? LogoPrint { get; set; }
        public string? ImgFooter { get; set; }
        public string? IdNumber { get; set; }
        public string? NoLabourOfficeFile { get; set; }
        public string? CommissionerName { get; set; }
        public int? Posting { get; set; }
        public int? LnkReInoviceInventory { get; set; }
        public int? LnkReBillInventroy { get; set; }
        public int? LnkTransfersInventory { get; set; }
        public string? Stamp { get; set; }
        public int? SalesAccountType { get; set; }
        public long? ProfitAndLossAccountId { get; set; }
        public string? ProfitAndLossAccountCode { get; set; }
        public string? ProfitAndLossAccountName { get; set; }
        public bool? UsingPurchaseAccount { get; set; }
        public long? PurchaseAccountId { get; set; }
        public string? PurchaseAccountCode { get; set; }
        public string? PurchaseAccountName { get; set; }
        public bool? VatEnable { get; set; }
        public string? VatNumber { get; set; }
        public long? SalesVatAccountId { get; set; }
        public string? SalesVatAccountCode { get; set; }
        public string? SalesVatAccountName { get; set; }
        public long? PurchasesVatAccountId { get; set; }
        public string? PurchasesVatAccountCode { get; set; }
        public string? PurchasesVatAccountName { get; set; }
        public long? AccountMembers { get; set; }
        public string? MemberAccountName { get; set; }
        public string? MemberAccountName2 { get; set; }
        public string? MemberAccountCode { get; set; }
    }
}
