using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Logix.Application.DTOs.WH
{
    public class WhTransactionsMasterDto
    {
        public long? TId { get; set; }
        public long? InventoryId { get; set; }
        public string? TCode { get; set; }
        public string? TDateHijri { get; set; }
        public string? TDateGregorian { get; set; }
        public string? TTime { get; set; }
        public string? TDescription { get; set; }
        public string? TBian { get; set; }
        public long? FinYear { get; set; }
        public long? FacilityId { get; set; }
        public long? BranchId { get; set; }
        public int? TransTypeId { get; set; }
        public int? StatusId { get; set; }
        public int? PaymentTypeId { get; set; }
        public string? ChequNo { get; set; }
        public string? ChequDateHijri { get; set; }
        public long? BankId { get; set; }
        public decimal? Amount { get; set; }
        public string? AmountWrite { get; set; }
        public long? ReferenceNo { get; set; }
        public long? CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public long? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public bool? IsDeleted { get; set; }
        public int? SupplierId { get; set; }
        public string? InvoiceCode { get; set; }
        public string? InvoiceDate { get; set; }
        public int? CustomerId { get; set; }
        public long? BranchId1 { get; set; }
        public int? CurrencyId { get; set; }
        public decimal? ExchangeRate { get; set; }
        public long? AccountId { get; set; }
        public long? EmpId { get; set; }
        public int? AccountType { get; set; }
        public string? TDateHijri1 { get; set; }
        public int? AutoManual { get; set; }
        public long? KeeperId { get; set; }
        public long? DriverId { get; set; }
        public long? CarId { get; set; }
        public long? InventoryId1 { get; set; }
        public int? DirectTransfer { get; set; }
        public long? ProjectId { get; set; }
        public int? InventoryTransfersType { get; set; }
        public string? Address { get; set; }
        public string? Note { get; set; }
        public int? RefranceType { get; set; }
        public long? RefranceId { get; set; }
        public int? DeliveryStatusId { get; set; }
        public int? VerifyType { get; set; }
        public string? VerifyOtpCode { get; set; }
        public DateTime? VerifiedOn { get; set; }
        public DateTime? VerifyOtpExpiredOn { get; set; }
        public string? VerifyDocumentUrl { get; set; }
        public long? VerifiedBy { get; set; }
        public string? VerifyMobile { get; set; }
        public long? SoId { get; set; }
        public string? SoCode { get; set; }
        public long? AppId { get; set; }
        public int? CatagoryId { get; set; }
    }
    public class WhTransactionsMasterEditDto
    {
        public long TId { get; set; }
        public long? InventoryId { get; set; }
        public string? TCode { get; set; }
        public string? TDateHijri { get; set; }
        public string? TDateGregorian { get; set; }
        public string? TTime { get; set; }
        public string? TDescription { get; set; }
        public string? TBian { get; set; }
        public long? FinYear { get; set; }
        public long? FacilityId { get; set; }
        public long? BranchId { get; set; }
        public int? TransTypeId { get; set; }
        public int? StatusId { get; set; }
        public int? PaymentTypeId { get; set; }
        public string? ChequNo { get; set; }
        public string? ChequDateHijri { get; set; }
        public long? BankId { get; set; }
        public decimal? Amount { get; set; }
        public string? AmountWrite { get; set; }
        public long? ReferenceNo { get; set; }
        public long? CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public long? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public bool? IsDeleted { get; set; }
        public int? SupplierId { get; set; }
        public string? InvoiceCode { get; set; }
        public string? InvoiceDate { get; set; }
        public int? CustomerId { get; set; }
        public long? BranchId1 { get; set; }
        public int? CurrencyId { get; set; }
        public decimal? ExchangeRate { get; set; }
        public long? AccountId { get; set; }
        public long? EmpId { get; set; }
        public int? AccountType { get; set; }
        public string? TDateHijri1 { get; set; }
        public int? AutoManual { get; set; }
        public long? KeeperId { get; set; }
        public long? DriverId { get; set; }
        public long? CarId { get; set; }
        public long? InventoryId1 { get; set; }
        public int? DirectTransfer { get; set; }
        public long? ProjectId { get; set; }
        public int? InventoryTransfersType { get; set; }
        public string? Address { get; set; }
        public string? Note { get; set; }
        public int? RefranceType { get; set; }
        public long? RefranceId { get; set; }
        public int? DeliveryStatusId { get; set; }
        public int? VerifyType { get; set; }
        public string? VerifyOtpCode { get; set; }
        public DateTime? VerifiedOn { get; set; }
        public DateTime? VerifyOtpExpiredOn { get; set; }
        public string? VerifyDocumentUrl { get; set; }
        public long? VerifiedBy { get; set; }
        public string? VerifyMobile { get; set; }
        public long? SoId { get; set; }
        public string? SoCode { get; set; }
        public long? AppId { get; set; }
        public int? CatagoryId { get; set; }
    }
    public class WhTransactionsMasterPurBillDto
    {
        public long TId { get; set; }
        public long? InventoryId { get; set; }
        public string? TCode { get; set; }
        public string? TDateHijri { get; set; }
        public string? TDateGregorian { get; set; }
        public string? TTime { get; set; }
        public string? TDescription { get; set; }
        public string? TBian { get; set; }
        public long? FinYear { get; set; }
        public long? FacilityId { get; set; }
        public long? BranchId { get; set; }
        public int? TransTypeId { get; set; }
        public int? StatusId { get; set; }
        public int? PaymentTypeId { get; set; }
        public string? ChequNo { get; set; }
        public string? ChequDateHijri { get; set; }
        public long? BankId { get; set; }
        public decimal? Amount { get; set; }
        public string? AmountWrite { get; set; }
        public long? ReferenceNo { get; set; }
        public long? CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public long? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public bool? IsDeleted { get; set; }
        public int? SupplierId { get; set; }
        public string? InvoiceCode { get; set; }
        public string? InvoiceDate { get; set; }
        public int? CustomerId { get; set; }
        public long? BranchId1 { get; set; }
        public int? CurrencyId { get; set; }
        public decimal? ExchangeRate { get; set; }
        public long? AccountId { get; set; }
        public long? EmpId { get; set; }
        public int? AccountType { get; set; }
        public string? TDateHijri1 { get; set; }
        public int? AutoManual { get; set; }
        public long? KeeperId { get; set; }
        public long? DriverId { get; set; }
        public long? CarId { get; set; }
        public long? InventoryId1 { get; set; }
        public int? DirectTransfer { get; set; }
        public long? ProjectId { get; set; }
        public int? InventoryTransfersType { get; set; }
        public string? Address { get; set; }
        public string? Note { get; set; }
        public int? RefranceType { get; set; }
        public long? RefranceId { get; set; }
        public int? DeliveryStatusId { get; set; }
        public int? VerifyType { get; set; }
        public string? VerifyOtpCode { get; set; }
        public DateTime? VerifiedOn { get; set; }
        public DateTime? VerifyOtpExpiredOn { get; set; }
        public string? VerifyDocumentUrl { get; set; }
        public long? VerifiedBy { get; set; }
        public string? VerifyMobile { get; set; }
        public long? SoId { get; set; }
        public string? SoCode { get; set; }
        public long? AppId { get; set; }
        public int? CatagoryId { get; set; }
        public WhTransactionsDetailePurBillDto? whDTran { get; set; }

    }
    public class WhTransactionsMasterPurBillEditDto
    {
        public long TId { get; set; }
        public long? InventoryId { get; set; }
        public string? TCode { get; set; }
        public string? TDateHijri { get; set; }
        public string? TDateGregorian { get; set; }
        public string? TTime { get; set; }
        public string? TDescription { get; set; }
        public string? TBian { get; set; }
        public long? FinYear { get; set; }
        public long? FacilityId { get; set; }
        public long? BranchId { get; set; }
        public int? TransTypeId { get; set; }
        public int? StatusId { get; set; }
        public int? PaymentTypeId { get; set; }
        public string? ChequNo { get; set; }
        public string? ChequDateHijri { get; set; }
        public long? BankId { get; set; }
        public decimal? Amount { get; set; }
        public string? AmountWrite { get; set; }
        public long? ReferenceNo { get; set; }
        public long? CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public long? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public bool? IsDeleted { get; set; }
        public int? SupplierId { get; set; }
        public string? InvoiceCode { get; set; }
        public string? InvoiceDate { get; set; }
        public int? CustomerId { get; set; }
        public long? BranchId1 { get; set; }
        public int? CurrencyId { get; set; }
        public decimal? ExchangeRate { get; set; }
        public long? AccountId { get; set; }
        public long? EmpId { get; set; }
        public int? AccountType { get; set; }
        public string? TDateHijri1 { get; set; }
        public int? AutoManual { get; set; }
        public long? KeeperId { get; set; }
        public long? DriverId { get; set; }
        public long? CarId { get; set; }
        public long? InventoryId1 { get; set; }
        public int? DirectTransfer { get; set; }
        public long? ProjectId { get; set; }
        public int? InventoryTransfersType { get; set; }
        public string? Address { get; set; }
        public string? Note { get; set; }
        public int? RefranceType { get; set; }
        public long? RefranceId { get; set; }
        public int? DeliveryStatusId { get; set; }
        public int? VerifyType { get; set; }
        public string? VerifyOtpCode { get; set; }
        public DateTime? VerifiedOn { get; set; }
        public DateTime? VerifyOtpExpiredOn { get; set; }
        public string? VerifyDocumentUrl { get; set; }
        public long? VerifiedBy { get; set; }
        public string? VerifyMobile { get; set; }
        public long? SoId { get; set; }
        public string? SoCode { get; set; }
        public long? AppId { get; set; }
        public int? CatagoryId { get; set; }
    }


	public class WhTransactionsMasterFilterDto
	{
		public long TId { get; set; }
		public long? InventoryId { get; set; }
		public string? TCode { get; set; }
		public string? ItemCode { get; set; }
		public string? AccountCode { get; set; }
		public string? TDateHijri { get; set; }
		public string? StartDate { get; set; }
		public string? EndDate { get; set; }
		public string? TDateGregorian { get; set; }
		public string? TTime { get; set; }
		public string? TDescription { get; set; }
		public string? TBian { get; set; }
		public long? FinYear { get; set; }
		public long? FacilityId { get; set; }
		public long? BranchId { get; set; }
		public int? TransTypeId { get; set; }
		public int? StatusId { get; set; }
		public int? PaymentTypeId { get; set; }
		public string? ChequNo { get; set; }
		public string? ChequDateHijri { get; set; }
		public long? BankId { get; set; }
		public decimal? Amount { get; set; }
		public string? AmountWrite { get; set; }
		public long? ReferenceNo { get; set; }
		public long? CreatedBy { get; set; }
		public DateTime? CreatedOn { get; set; }
		public long? ModifiedBy { get; set; }
		public DateTime? ModifiedOn { get; set; }
		public bool? IsDeleted { get; set; }
		public int? SupplierId { get; set; }
		public string? InvoiceCode { get; set; }
		public string? InvoiceDate { get; set; }
		public int? CustomerId { get; set; }
		public long? BranchId1 { get; set; }
		public int? CurrencyId { get; set; }
		public decimal? ExchangeRate { get; set; }
		public long? AccountId { get; set; }
		public long? EmpId { get; set; }
		public int? AccountType { get; set; }
		public string? TDateHijri1 { get; set; }
		public int? AutoManual { get; set; }
		public long? KeeperId { get; set; }
		public long? DriverId { get; set; }
		public long? CarId { get; set; }
		public long? InventoryId1 { get; set; }
		public int? DirectTransfer { get; set; }
		public long? ProjectId { get; set; }
		public int? InventoryTransfersType { get; set; }
		public string? Address { get; set; }
		public string? Note { get; set; }
		public int? RefranceType { get; set; }
		public long? RefranceId { get; set; }
		public int? DeliveryStatusId { get; set; }
		public int? VerifyType { get; set; }
		public string? VerifyOtpCode { get; set; }
		public DateTime? VerifiedOn { get; set; }
		public DateTime? VerifyOtpExpiredOn { get; set; }
		public string? VerifyDocumentUrl { get; set; }
		public long? VerifiedBy { get; set; }
		public string? VerifyMobile { get; set; }
		public long? SoId { get; set; }
		public string? SoCode { get; set; }
		public long? AppId { get; set; }
		public int? CatagoryId { get; set; }
	}
}
